=== miguelzapaton/ehn-dcc-schema-json-validator/resources-tmp/jsonschema/1.0.1/DGC.Schema.Combined.Full.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://id.uvci.eu/DGC.schema.json",
  "title": "EU DGC",
  "description": "EU Digital Green Certificate",
  "$comment": "Schema version 1.0.1",
  "required": [
    "ver",
    "nam",
    "dob"
  ],
  "type": "object",
  "properties": {
    "ver": {
      "title": "Schema version",
      "description": "Version of the schema, according to Semantic versioning (ISO, https://semver.org/ version 2.0.0 or newer)",
      "type": "string",
      "pattern": "^\\d+.\\d+.\\d+$",
      "examples": [
        "1.0.0"
      ]
    },
    "nam": {
      "description": "Surname(s), given name(s) - in that order",
      "required": [
        "fnt"
      ],
      "type": "object",
      "properties": {
        "fn": {
          "title": "Family name",
          "description": "The family or primary name(s) of the person addressed in the certificate",
          "type": "string",
          "maxLength": 50,
          "examples": [
            "d'Červenková Panklová"
          ]
        },
        "fnt": {
          "title": "Standardised family name",
          "description": "The family name(s) of the person transliterated",
          "type": "string",
          "pattern": "^[A-Z<]*$",
          "maxLength": 50,
          "examples": [
            "DCERVENKOVA<PANKLOVA"
          ]
        },
        "gn": {
          "title": "Given name",
          "description": "The given name(s) of the person addressed in the certificate",
          "type": "string",
          "maxLength": 50,
          "examples": [
            "Jiřina-Maria Alena"
          ]
        },
        "gnt": {
          "title": "Standardised given name",
          "description": "The given name(s) of the person transliterated",
          "type": "string",
          "pattern": "^[A-Z<]*$",
          "maxLength": 50,
          "examples": [
            "JIRINA<MARIA<ALENA"
          ]
        }
      }
    },
    "dob": {
      "title": "Date of birth",
      "description": "Date of Birth of the person addressed in the DGC. ISO 8601 date format restricted to range 1900-2099",
      "type": "string",
      "format": "date",
      "pattern": "(19|20)\\d{2}-\\d{2}-\\d{2}",
      "examples": [
        "1979-04-14"
      ]
    },
    "v": {
      "description": "Vaccination Group",
      "type": "array",
      "items": {
        "description": "Vaccination Entry",
        "required": [
          "tg",
          "vp",
          "mp",
          "ma",
          "dn",
          "sd",
          "dt",
          "co",
          "is",
          "ci"
        ],
        "type": "object",
        "properties": {
          "tg": {
            "description": "disease or agent targeted",
            "type": "string",
            "oneOf": [
              {
                "const": "840539006"
              }
            ]
          },
          "vp": {
            "description": "vaccine or prophylaxis",
            "type": "string",
            "oneOf": [
              {
                "const": "1119305005"
              },
              {
                "const": "1119349007"
              },
              {
                "const": "J07BX03"
              }
            ]
          },
          "mp": {
            "description": "vaccine medicinal product",
            "type": "string",
            "oneOf": [
              {
                "const": "EU/1/20/1528"
              },
              {
                "const": "EU/1/20/1507"
              },
              {
                "const": "EU/1/21/1529"
              },
              {
                "const": "EU/1/20/1525"
              },
              {
                "const": "CVnCoV"
              },
              {
                "const": "Sputnik-V"
              },
              {
                "const": "Convidecia"
              },
              {
                "const": "EpiVacCorona"
              },
              {
                "const": "BBIBP-CorV"
              },
              {
                "const": "Inactivated-SARS-CoV-2-Vero-Cell"
              },
              {
                "const": "CoronaVac"
              },
              {
                "const": "Covaxin"
              }
            ]
          },
          "ma": {
            "description": "Marketing Authorization Holder - if no MAH present, then manufacturer",
            "type": "string",
            "oneOf": [
              {
                "const": "ORG-100001699"
              },
              {
                "const": "ORG-100030215"
              },
              {
                "const": "ORG-100001417"
              },
              {
                "const": "ORG-100031184"
              },
              {
                "const": "ORG-100006270"
              },
              {
                "const": "ORG-100013793"
              },
              {
                "const": "ORG-100020693"
              },
              {
                "const": "ORG-100010771"
              },
              {
                "const": "ORG-100024420"
              },
              {
                "const": "ORG-100032020"
              },
              {
                "const": "Gamaleya-Research-Institute"
              },
              {
                "const": "Vector-Institute"
              },
              {
                "const": "Sinovac-Biotech"
              },
              {
                "const": "Bharat-Biotech"
              }
            ]
          },
          "dn": {
            "description": "Dose Number",
            "type": "integer",
            "minimum": 1,
            "maximum": 9
          },
          "sd": {
            "description": "Total Series of Doses",
            "type": "integer",
            "minimum": 1,
            "maximum": 9
          },
          "dt": {
            "description": "Date of Vaccination",
            "type": "string",
            "format": "date",
            "$comment": "SemanticSG: constrain to specific date range?"
          },
          "co": {
            "description": "Country of Vaccination",
            "type": "string",
            "pattern": "[A-Z]{1,10}"
          },
          "is": {
            "description": "Certificate Issuer",
            "type": "string",
            "maxLength": 50
          },
          "ci": {
            "description": "Unique Certificate Identifier: UVCI",
            "type": "string",
            "maxLength": 50
          }
        }
      },
      "minItems": 1
    },
    "t": {
      "description": "Test Group",
      "type": "array",
      "items": {
        "description": "Test Entry",
        "required": [
          "tg",
          "tt",
          "sc",
          "tr",
          "tc",
          "co",
          "is",
          "ci"
        ],
        "type": "object",
        "properties": {
          "tg": {
            "description": "EU eHealthNetwork: Value Sets for Digital Green Certificates. version 1.0, 2021-04-16, section 2.1",
            "type": "string",
            "oneOf": [
              {
                "const": "840539006"
              }
            ]
          },
          "tt": {
            "description": "Type of Test",
            "type": "string",
            "oneOf": [
              {
                "const": "LP6464-4"
              },
              {
                "const": "LP217198-3"
              }
            ]
          },
          "nm": {
            "description": "NAA Test Name",
            "type": "string"
          },
          "ma": {
            "description": "RAT Test name and manufacturer",
            "type": "string",
            "oneOf": [
              {
                "const": "344"
              },
              {
                "const": "345"
              },
              {
                "const": "1065"
              },
              {
                "const": "1097"
              },
              {
                "const": "1162"
              },
              {
                "const": "1173"
              },
              {
                "const": "1180"
              },
              {
                "const": "1218"
              },
              {
                "const": "1223"
              },
              {
                "const": "1232"
              },
              {
                "const": "1242"
              },
              {
                "const": "1244"
              },
              {
                "const": "1268"
              },
              {
                "const": "1271"
              },
              {
                "const": "1278"
              },
              {
                "const": "1304"
              },
              {
                "const": "1331"
              },
              {
                "const": "1333"
              },
              {
                "const": "1341"
              },
              {
                "const": "1343"
              },
              {
                "const": "1360"
              },
              {
                "const": "1363"
              },
              {
                "const": "1481"
              },
              {
                "const": "1484"
              },
              {
                "const": "1489"
              },
              {
                "const": "1767"
              }
            ]
          },
          "sc": {
            "description": "Date/Time of Sample Collection",
            "type": "string",
            "format": "date-time"
          },
          "dr": {
            "description": "Date/Time of Test Result",
            "type": "string",
            "format": "date-time"
          },
          "tr": {
            "description": "Test Result",
            "type": "string",
            "oneOf": [
              {
                "const": "260373001"
              },
              {
                "const": "260415000"
              }
            ]
          },
          "tc": {
            "description": "Testing Centre",
            "type": "string",
            "maxLength": 50
          },
          "co": {
            "description": "Country of Test",
            "type": "string",
            "pattern": "[A-Z]{1,10}"
          },
          "is": {
            "description": "Certificate Issuer",
            "type": "string",
            "maxLength": 50
          },
          "ci": {
            "description": "Unique Certificate Identifier, UVCI",
            "type": "string",
            "maxLength": 50
          }
        }
      },
      "minItems": 1
    },
    "r": {
      "description": "Recovery Group",
      "type": "array",
      "items": {
        "description": "Recovery Entry",
        "required": [
          "tg",
          "fr",
          "co",
          "is",
          "df",
          "du",
          "ci"
        ],
        "type": "object",
        "properties": {
          "tg": {
            "description": "EU eHealthNetwork: Value Sets for Digital Green Certificates. version 1.0, 2021-04-16, section 2.1",
            "type": "string",
            "oneOf": [
              {
                "const": "840539006"
              }
            ]
          },
          "fr": {
            "description": "ISO 8601 Date of First Positive Test Result",
            "type": "string",
            "format": "date"
          },
          "co": {
            "description": "Country of Test",
            "type": "string",
            "pattern": "[A-Z]{1,10}"
          },
          "is": {
            "description": "Certificate Issuer",
            "type": "string",
            "maxLength": 50
          },
          "df": {
            "description": "ISO 8601 Date: Certificate Valid From",
            "type": "string",
            "format": "date"
          },
          "du": {
            "description": "Certificate Valid Until",
            "type": "string",
            "format": "date"
          },
          "ci": {
            "description": "Unique Certificate Identifier, UVCI",
            "type": "string",
            "maxLength": 50
          }
        }
      },
      "minItems": 1
    }
  }
}

=== miguelzapaton/ehn-dcc-schema-json-validator/data/examples-latest/examples/test/transliterated.json
{
  "ver": "1.3.0",
  "nam": {
    "fn": "ابو بكر محمد بن زكريا الرازي",
    "fnt": "ABW<BKR<MXHMD<BN<ZKRYA<ALRAZY",
    "gn": "ناصر",
    "gnt": "NAXSSR"
  },
  "dob": "1964-01-01",
  "t": [
    {
      "tg": "840539006",
      "tt": "LP6464-4",
      "nm": "ELITechGroup, SARS-CoV-2 ELITe MGB® Kit",
      "sc": "2021-06-11T17:30:00Z",
      "tr": "260415000",
      "tc": "Example Test Corp, Big City",
      "co": "NL",
      "is": "Ministry of Health Welfare and Sport",
      "ci": "URN:UVCI:01:NL:DADFCC47C7334E45A906DB12FD859FB7#1"
    }
  ]
}

=== miguelzapaton/ehn-dcc-schema-json-validator/data/examples-latest/examples/recovery/transliterated.json
{
  "ver": "1.3.0",
  "nam": {
    "fn": "ابو بكر محمد بن زكريا الرازي",
    "fnt": "ABW<BKR<MXHMD<BN<ZKRYA<ALRAZY",
    "gn": "ناصر",
    "gnt": "NAXSSR"
  },
  "dob": "1964-01-01",
  "r": [
    {
      "tg": "840539006",
      "fr": "2021-06-01",
      "co": "NL",
      "is": "Ministry of Health Welfare and Sport",
      "df": "2021-06-12",
      "du": "2021-11-28",
      "ci": "URN:UVCI:01:NL:DADFCC47C7334E45A906DB12FD859FB7#1"
    }
  ]
}

=== miguelzapaton/ehn-dcc-schema-json-validator/data/examples-20210611/test/valid/V-min-data.json
{
  "ver": "1.3.0",
  "nam": {
    "fn": "Li",
    "fnt": "LI"
  },
  "dob": "1970",
  "v": [
    {
      "tg": "840539006",
      "vp": "1119305005",
      "mp": "EU/1/20/1525",
      "ma": "ORG-100001417",
      "dn": 1,
      "sd": 1,
      "dt": "2021-06-11",
      "co": "NL",
      "is": "Ministry of Health Welfare and Sport",
      "ci": "01:NL:1312D00"
    }
  ]
}

=== miguelzapaton/ehn-dcc-schema-json-validator/examples/vaccination/transliterated.json
{
  "ver": "1.3.0",
  "nam": {
    "fn": "ابو بكر محمد بن زكريا الرازي",
    "fnt": "ABW<BKR<MXHMD<BN<ZKRYA<ALRAZY",
    "gn": "ناصر",
    "gnt": "NAXSSR"
  },
  "dob": "1964-01-01",
  "v": [
    {
      "tg": "840539006",
      "vp": "1119349007",
      "mp": "EU/1/20/1507",
      "ma": "ORG-100031184",
      "dn": 1,
      "sd": 2,
      "dt": "2021-06-11",
      "co": "NL",
      "is": "Ministry of Health Welfare and Sport",
      "ci": "URN:UVCI:01:NL:DADFCC47C7334E45A906DB12FD859FB7"
    }
  ]
}

=== miguelzapaton/ehn-dcc-schema-json-validator/data/examples-20210611/test/valid/R-min-data.json
{
  "ver": "1.3.0",
  "nam": {
    "fn": "Li",
    "fnt": "LI"
  },
  "dob": "1970",
  "r": [
    {
      "tg": "840539006",
      "fr": "2021-01-01",
      "co": "NL",
      "is": "Ministry of Health Welfare and Sport",
      "df": "2021-06-12",
      "du": "2021-11-28",
      "ci": "01:NL:1312D00"
    }
  ]
}

=== miguelzapaton/ehn-dcc-schema-json-validator/data/examples-latest/test/valid/R-dates2.json
{
  "ver": "1.3.0",
  "nam": {
    "fn": "Smith-Jones",
    "fnt": "SMITH<JONES",
    "gn": "Charles Edward",
    "gnt": "CHARLES<EDWARD"
  },
  "dob": "1964-01",
  "r": [
    {
      "tg": "840539006",
      "fr": "2021-06-01",
      "co": "UNHCR",
      "is": "United Nations HCR",
      "df": "2021-06-12",
      "du": "2021-11-28",
      "ci": "URN#UVCI#01#NL#DADFCC47C7334E45A906DB12FD859FB7"
    }
  ]
}
